<?php
/**
 * Created by:  Milan Simek
 * Company:     Plugin Company
 *
 * LICENSE: http://plugin.company/docs/magento-extensions/magento-extension-license-agreement
 *
 * YOU WILL ALSO FIND A PDF COPY OF THE LICENSE IN THE DOWNLOADED ZIP FILE
 *
 * FOR QUESTIONS AND SUPPORT
 * PLEASE DON'T HESITATE TO CONTACT US AT:
 *
 * SUPPORT@PLUGIN.COMPANY
 */
?>
<script>
    require([
        "jquery",
        "mage/calendar"
    ], function($){
        $(".date-input").calendar({
            buttonText:"<?php echo __('Select Date') ?>",
            outputDateFormat: 'yy-mm-dd',
            inputDateFormat: 'yy-mm-dd',
            pickerDateTimeFormat: 'yy-mm-dd',
            showsTime: false,
            dateFormat: $.datepicker.ATOM
        });
    });
</script>